# Generated by Django 4.2.7 on 2023-11-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_availeble',
            new_name='is_active',
        ),
    ]
