# Generated by Django 4.2.7 on 2023-12-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numper',
            new_name='phone_number',
        ),
    ]
