# Generated by Django 3.1 on 2023-11-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20231111_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slog',
            new_name='slug',
        ),
    ]
